language: java

jdk:
   - oraclejdk7

services: mysql

before_script:
   - mysql -e 'create database test;'
   - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'root'@'%' IDENTIFIED BY 'root';"


script: cd HibernateLearn && mvn test
