language: java

jdk:
   - oraclejdk7

services: mysql

before_script:
   - echo "USE mysql;\n UPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
   - mysql -e 'create database test;'


script: cd HibernateLearn && mvn test
